<?xml version ='1.0' encoding ='UTF-8' ?> 
<definitions name='addition' 
  targetNamespace='http://example.org/addition' 
  xmlns:tns='http://example.org/addition' 
  xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' 
  xmlns:xsd='http://www.w3.org/2001/XMLSchema' 
  xmlns:soapenc='http://schemas.xmlsoap.org/soap/encoding/' 
  xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' 
  xmlns='http://schemas.xmlsoap.org/wsdl/'> 

	<message name='getResultRequest'> 
	  <part name='integer1' type='xsd:int'/>
	  <part name='integer2' type='xsd:int'/>
	</message> 
	<message name='getResultResponse'> 
	  <part name='result' type='xsd:int'/> 
	</message> 
	
	<portType name='getResultPortType'> 
	  <operation name='add'> 
	    <input message='tns:getResultRequest'/> 
	    <output message='tns:getResultResponse'/> 
	  </operation>
	  <operation name='substract'> 
	    <input message='tns:getResultRequest'/> 
	    <output message='tns:getResultResponse'/> 
	  </operation>  
	</portType> 
	
	<binding name='getResultBinding' type='tns:getResultPortType'> 
	  <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/> 
	  <operation name='add'> 
	    <soap:operation soapAction='urn:xmethods-delayed-quotes#add'/> 
	    <input> 
	      <soap:body use='encoded' namespace='urn:xmethods-delayed-calcul' 
	      	encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
	    </input> 
	    <output> 
	      <soap:body use='encoded' namespace='urn:xmethods-delayed-calcul' 
	        encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
	    </output> 
	  </operation>
	  <operation name='substract'> 
	    <soap:operation soapAction='urn:xmethods-delayed-quotes#substract'/> 
	    <input> 
	      <soap:body use='encoded' namespace='urn:xmethods-delayed-calcul' 
	      	encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
	    </input> 
	    <output> 
	      <soap:body use='encoded' namespace='urn:xmethods-delayed-calcul' 
	        encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/> 
	    </output> 
	  </operation>

	</binding> 
	
	<service name='getResultService'> 
	  <port name='getResultPort' binding='getResultBinding'> 
	    <soap:address location='http://172.17.50.155/soap-addition/serveur-addition.php'/> 
	  </port> 
	</service> 
</definitions>